# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'dividend-analyser' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for dividend-analyser
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'Alamofire', '~> 5.1'
  pod "SwiftCSV"
  pod 'Kingfisher', '~> 5.0'
  pod 'Firebase/Storage'
  pod 'SwiftKeychainWrapper'

  target 'dividend-analyserTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'dividend-analyserUITests' do
    # Pods for testing
  end

end
